first draft aex-5
aeternity/AEXs pull request #14
Opened 2019-05-14 07:16 UTC by shekhar-shubhendu

2019-05-14 18:05 UTC, knarz requested changes

2019-05-14 18:05 UTC, knarz commented on AEXS/aex-5.md
> +The purpose of AEXs is to provide specification and json-rpc compatible messages required for inter wallet communication channel.
Either "for inter wallet communication channel**s**" or "for **an** inter wallet communication channel"

2019-05-14 18:05 UTC, knarz commented on AEXS/aex-5.md
> +3. If, SDK needs the wallet to sign the transaction it asks the wallet
s/,//

2019-05-14 18:05 UTC, knarz commented on AEXS/aex-5.md
> +3. If, SDK needs the wallet to sign the transaction it asks the wallet
s/,//

2019-05-14 18:05 UTC, knarz commented on AEXS/aex-5.md
> +2. Wallet returns it's personal address and other account address it may help the SDK in getting signature for.
What would a "personal address" be in this context?
And maybe reformulate: Wallet returns its personal address and possibly other addresses it can provide signatures for.

2019-05-14 18:05 UTC, knarz commented on AEXS/aex-5.md
> +- `wallet.get.address`: to ask the connected wallet for its address
s/to//

2019-05-14 18:05 UTC, knarz commented on AEXS/aex-5.md
> +- `wallet.channel.initiate`: initiate request to open a communication channel. The request contains an identifier that will be used by either party to recognize and process incoming messages. The gen
Maybe just add a small note that the `id` must match for subsequent messages

2019-05-14 18:05 UTC, knarz commented on AEXS/aex-5.md
> +4. Wallet performs steps in the below order
performs the following steps in order

2019-05-14 18:05 UTC, knarz commented on AEXS/aex-5.md
> +    2. else it checks if it holds direct link to the wallet that can sign the transaction and forwards the request to it.
"if it holds **a** direct link"

2019-05-15 07:01 UTC, shekhar-shubhendu commented on AEXS/aex-5.md
> +2. Wallet returns it's personal address and other account address it may help the SDK in getting signature for.
The wallet will not be able to "provide" signatures but it can help the SDK by forwarding the signing requests to the connected wallets.

2019-05-15 08:20 UTC, shekhar-shubhendu commented
@knarz please review

2019-05-15 16:58 UTC, knarz approved these changes

2019-05-15 16:58 UTC, merged