Add NFT proposal
aeternity/AEXs pull request #143
Opened 2021-12-15 09:05 UTC by arjanvaneersel

When opening a pull request to submit a new AEX, please use the suggested template: [https://github.com/aeternity/AEXs/blob/master/aex-X.md](https://github.com/aeternity/AEXs/blob/master/aex-X.md)

2021-12-15 09:29 UTC, mradkov commented on .vscode/settings.json
> +}
Can you exclude this file from the PR?

2021-12-15 09:30 UTC, mradkov commented on AEXS/aex-nft.md
> +```sofia
```suggestion
```sophia
```

2021-12-15 09:30 UTC, mradkov commented on AEXS/aex-nft.md
> +    entrypoint on_nft_received : (address, address, int, option(string)) => unit
```suggestion
```sophia
contract interface NFTReceiver = 
    entrypoint on_nft_received : (address, address, int, option(string)) => unit
```
```

2021-12-15 09:31 UTC, mradkov commented on AEXS/aex-nft.md
> +```
```suggestion
```sophia
```

2021-12-15 09:31 UTC, mradkov commented on AEXS/aex-nft.md
> +```entrypoint metadata(id int): option(metadata)```
```suggestion
```sophia
entrypoint metadata(id int): option(metadata)
```
```

2021-12-15 09:31 UTC, mradkov commented on AEXS/aex-nft.md
> +```
```suggestion
```sophia
```

2021-12-15 09:32 UTC, mradkov requested changes
Let's keep the formatting consistent.

2021-12-15 10:09 UTC, arjanvaneersel commented on .vscode/settings.json
> +}
Done that

2021-12-15 13:45 UTC, marc0olo commented on AEXS/aex-nft.md
> +```
I think something went wrong with the old suggestion. I also prefer `NFTs` over `NFT tokens` as the "T" already stands for token.

```suggestion
Deals with receiving NFTs on behalf of a smart contract. A smart contract MUST implement this interface to be able to receive NFTs. Mint and transfer transactions will invoke the `on_nft_received` function.

```sophia
contract interface NFTReceiver = 
    entrypoint on_nft_received : (address, address, int, option(string)) => unit
```
```

2021-12-16 01:39 UTC, marc0olo commented on AEXS/aex-nft.md
> +Deals with receiving NFT tokens on behalf of a smart contract. Contracts receiving NFT tokens should implement this interface. Mint and transfer transactions will invoke the `on_nft_received` functio
I also prefer `NFTs` over `NFT tokens` as the "T" already stands for token.

```suggestion
Deals with receiving NFTs on behalf of a smart contract. A smart contract MUST implement this interface to be able to receive NFTs. Mint and transfer transactions will invoke the `on_nft_received` function.
```

2021-12-16 01:42 UTC, marc0olo commented on AEXS/aex-nft.md
> +| parameter | type |
formatting was broken

```suggestion
```sophia
entrypoint metadata(id int): option(metadata)
```

| parameter | type |
```

2021-12-16 01:44 UTC, marc0olo commented
@arjanvaneersel The suggestions somehow cannot deal with this. But in some sophia codeblocks the ``` on the bottom are missing. This breaks the formatting,

2021-12-29 11:11 UTC, omar-saadoun reviewed
Small editions to text description

2021-12-29 11:11 UTC, omar-saadoun commented on AEXS/aex-nft.md
> +The following standard describes standard interfaces for non-fungible tokens. The proposal contains a primary interface and secondary interfaces for optional functionality that not everyone might nee
Small text edit : 
```suggestion
The following standard describes standard interfaces for non-fungible tokens. The proposal contains a primary and secondary interfaces for optional functionality that not everyone might need. 
```

2021-12-30 16:50 UTC, thepiwo commented
for me it looks good with the comments from @omar-saadoun and @marc0olo adressed

2022-01-03 21:46 UTC, marc0olo commented
@arjanvaneersel I saw you accepted some changes. there is still the formatting issue I mentioned in my comment.

can we agree on AEX-141 @thepiwo, @omar-saadoun? it's the number of the issue and got most votes on discord.

if so you can also change the filename and the `aexX` and `aex-X` placeholders in the standard definition.

after that I think we are ready to go and can merge it finally =)

2022-01-05 12:27 UTC, arjanvaneersel commented
@marc0olo There's no change request with your comments, at least I don't see a button to accept your comments.

2022-01-05 12:56 UTC, marc0olo commented
Hi @arjanvaneersel, I am talking about the following comment: https://github.com/aeternity/AEXs/pull/143#issuecomment-995363684

If you address this and change the placeholders and file accordingly to fit the `AEX-141` we can merge =)

2022-01-10 16:26 UTC, marc0olo commented
@arjanvaneersel when will you be able to make the last changes? you can also provide me the rights to adjust this on your branch if you want.

how should we proceed with the implementation? I will probably find somebody of the team to tackle this if that is ok for you. we need to move forward a bit faster on that topic

2022-01-27 07:31 UTC, marc0olo requested changes
few more changes and we should finally be ready to merge =) ... thanks Arjan!

2022-01-27 07:31 UTC, marc0olo commented on AEXS/aex-141.md
>  # AEX Non-Fungible Token Standard
```suggestion
# AEX-141: Non-Fungible Token Standard
```

2022-01-27 07:31 UTC, marc0olo commented on AEXS/aex-141.md
> +```
```suggestion
### aex141_extensions\(\)

This function **returns** a hardcoded list of all implemented extensions on the deployed contract.

```sophia
entrypoint aex141_extensions() : list(string)
```
```

2022-01-27 07:31 UTC, marc0olo commented on AEXS/aex-141.md
> +    entrypoint aexX_extensions() : list(string)
```suggestion
    entrypoint aex141_extensions() : list(string)
```

2022-01-27 07:31 UTC, marc0olo commented on AEXS/aex-141.md
> +Status: Draft
```suggestion
Discussions-To: https://forum.aeternity.com/t/aeternity-nft-token-standard/9781
Status: Review
```

2022-01-27 07:51 UTC, marc0olo approved these changes
we did it, finally! 🥳  thanks @arjanvaneersel! :-)

2022-01-27 07:51 UTC, merged